/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hospitalmgmtportal;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ASUS
 */
public class FullWindow extends javax.swing.JPanel {

    /**
     * Creates new form FullWindow
     */
    public FullWindow() {
        initComponents();
    }
    
    void createWindow() 
    {    
      JFrame frame = new JFrame("Hospital Management");
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      createUI(frame);
      frame.setSize(600, 600);      
      frame.setLocationRelativeTo(null);  
      frame.setVisible(true);
    }

    void createUI(final JFrame frame)
    {  
      JPanel buttonPanel = new JPanel(new FlowLayout());
      buttonPanel.add(new JLabel("Login:"));
      buttonPanel.add(new JLabel("*********"));
      buttonPanel.add(new JLabel("Username:"));
      buttonPanel.add(new JTextField(10));
      buttonPanel.add(new JLabel("Password:"));
      buttonPanel.add(new JTextField(10));
      buttonPanel.add(new JButton("OK"));
      buttonPanel.add(new JButton("Cancel"));  
      
      JPanel textBoxPanel = new JPanel(new FlowLayout());
      textBoxPanel.add(new JLabel("Name:"));
      textBoxPanel.add(new JTextField(20));
      JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, buttonPanel, textBoxPanel);
      splitPane.setOneTouchExpandable(true);
      splitPane.setDividerLocation(150);
      frame.getContentPane().add(splitPane, BorderLayout.CENTER);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
