/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.util.List;
import model.Citylist;
import model.City;
import model.PatientList;
import model.HospitalsList;
import model.DoctorsList;
import model.PersonHistory;
import model.Community;
import model.VitalSignsHistory;

/**
 *
 * @author hindupurv
 */
public class loginPage extends javax.swing.JFrame {

    /**
     * Creates new form loginPage
     */
    PersonHistory history = new PersonHistory();
    VitalSignsHistory history1 = new VitalSignsHistory();
    private HospitalsList hospitalsList;
    private PatientList patient;
    private DoctorsList doctorslist;
    private Citylist cityList; 
    private City city; 
    private Community community; 
    protected List<Community> communities;
    
    public loginPage() {
        initComponents();
        hospitalsList = new HospitalsList();
        patient = new PatientList();
        doctorslist = new DoctorsList();
        //community = new Community();
        //communities.add(community);
        //city.setCommunities(communities);
        cityList = new Citylist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HospitalImg = new javax.swing.JLabel();
        HospitalAdminLogo = new javax.swing.JLabel();
        HospitalAdminBtn = new javax.swing.JButton();
        PatientLogo = new javax.swing.JLabel();
        PatientBtn = new javax.swing.JButton();
        SystemAdminLogo = new javax.swing.JLabel();
        SystemAdminBtn = new javax.swing.JButton();
        PersonBtn = new javax.swing.JButton();
        DoctorLogo = new javax.swing.JLabel();
        DoctorBtn = new javax.swing.JButton();
        CommunityAdminLogo2 = new javax.swing.JLabel();
        CommunityAdminBtn1 = new javax.swing.JButton();
        CommunityAdminLogo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        HospitalImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backglogo.jpg"))); // NOI18N
        jPanel1.add(HospitalImg);
        HospitalImg.setBounds(10, 240, 440, 270);

        HospitalAdminLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HospitalAdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hospadmin.jpg"))); // NOI18N
        jPanel1.add(HospitalAdminLogo);
        HospitalAdminLogo.setBounds(800, 60, 120, 130);

        HospitalAdminBtn.setText("Hospital Admin");
        HospitalAdminBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HospitalAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(HospitalAdminBtn);
        HospitalAdminBtn.setBounds(800, 210, 130, 30);

        PatientLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PatientLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient.jpg"))); // NOI18N
        jPanel1.add(PatientLogo);
        PatientLogo.setBounds(810, 270, 120, 110);

        PatientBtn.setText("Patient");
        PatientBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PatientBtn);
        PatientBtn.setBounds(810, 410, 130, 30);

        SystemAdminLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SystemAdminLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/systemadmin.jpg"))); // NOI18N
        jPanel1.add(SystemAdminLogo);
        SystemAdminLogo.setBounds(550, 60, 130, 120);

        SystemAdminBtn.setText("System Admin");
        SystemAdminBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SystemAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemAdminBtnActionPerformed(evt);
            }
        });
        jPanel1.add(SystemAdminBtn);
        SystemAdminBtn.setBounds(550, 210, 130, 30);

        PersonBtn.setText("Person");
        PersonBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonBtnActionPerformed(evt);
            }
        });
        jPanel1.add(PersonBtn);
        PersonBtn.setBounds(820, 610, 130, 30);

        DoctorLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DoctorLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doctorlogo.jpg"))); // NOI18N
        jPanel1.add(DoctorLogo);
        DoctorLogo.setBounds(550, 270, 120, 110);

        DoctorBtn.setText("Doctor");
        DoctorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorBtn);
        DoctorBtn.setBounds(550, 410, 130, 30);

        CommunityAdminLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CommunityAdminLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/person.jpg"))); // NOI18N
        jPanel1.add(CommunityAdminLogo2);
        CommunityAdminLogo2.setBounds(810, 460, 130, 140);

        CommunityAdminBtn1.setText("Community Admin");
        CommunityAdminBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CommunityAdminBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityAdminBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(CommunityAdminBtn1);
        CommunityAdminBtn1.setBounds(550, 610, 130, 30);

        CommunityAdminLogo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CommunityAdminLogo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/commlogo.jpg"))); // NOI18N
        jPanel1.add(CommunityAdminLogo3);
        CommunityAdminLogo3.setBounds(550, 460, 130, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HospitalAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalAdminBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame userlogpanel = new LoginFrame(hospitalsList,patient,doctorslist,cityList);
        userlogpanel.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_HospitalAdminBtnActionPerformed

    private void PatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame userlogpanel = new LoginFrame(hospitalsList,patient,doctorslist,cityList);
        userlogpanel.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_PatientBtnActionPerformed

    private void DoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame userlogpanel = new LoginFrame(hospitalsList,patient,doctorslist,cityList);
        userlogpanel.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_DoctorBtnActionPerformed

    private void SystemAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemAdminBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame userlogpanel = new LoginFrame(hospitalsList,patient,doctorslist,cityList);
        userlogpanel.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_SystemAdminBtnActionPerformed

    private void CommunityAdminBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityAdminBtn1ActionPerformed
        // TODO add your handling code here:
        LoginFrame userlogpanel = new LoginFrame(hospitalsList,patient,doctorslist,cityList);
        userlogpanel.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_CommunityAdminBtn1ActionPerformed

    private void PersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonBtnActionPerformed
        // TODO add your handling code here:
        PersonFrame personpanel = new PersonFrame (history);
        personpanel.setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_PersonBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new loginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommunityAdminBtn1;
    private javax.swing.JLabel CommunityAdminLogo2;
    private javax.swing.JLabel CommunityAdminLogo3;
    private javax.swing.JButton DoctorBtn;
    private javax.swing.JLabel DoctorLogo;
    private javax.swing.JButton HospitalAdminBtn;
    private javax.swing.JLabel HospitalAdminLogo;
    private javax.swing.JLabel HospitalImg;
    private javax.swing.JButton PatientBtn;
    private javax.swing.JLabel PatientLogo;
    private javax.swing.JButton PersonBtn;
    private javax.swing.JButton SystemAdminBtn;
    private javax.swing.JLabel SystemAdminLogo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
