/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddCommunityAdminPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String commAdminName = "";
    String commAdminCity = "";
    String commAdminEmail = "";
    Boolean submitAdminDetail = false;
    
    public AddCommunityAdminPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CommunityPageLabel = new javax.swing.JLabel();
        CommunityNameLabel = new javax.swing.JLabel();
        CommunityNameInput = new javax.swing.JTextField();
        CommunityAdminEmailLabel = new javax.swing.JLabel();
        CommunityAdminEmailInput = new javax.swing.JTextField();
        CommunityAdminCityLabel = new javax.swing.JLabel();
        CommunityAdminCityInput = new javax.swing.JTextField();
        SubmitCommunityButton = new javax.swing.JButton();
        CloseCommunityButton = new javax.swing.JButton();
        BackCommunityButton = new javax.swing.JButton();
        BackgroundAdminPortal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        CommunityPageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CommunityPageLabel.setText("Community Admin Information Form:");
        getContentPane().add(CommunityPageLabel);
        CommunityPageLabel.setBounds(400, 210, 470, 32);

        CommunityNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CommunityNameLabel.setText("Name:");
        getContentPane().add(CommunityNameLabel);
        CommunityNameLabel.setBounds(406, 270, 40, 32);

        CommunityNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(CommunityNameInput);
        CommunityNameInput.setBounds(460, 270, 150, 30);

        CommunityAdminEmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CommunityAdminEmailLabel.setText("Email:");
        getContentPane().add(CommunityAdminEmailLabel);
        CommunityAdminEmailLabel.setBounds(410, 370, 50, 32);

        CommunityAdminEmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityAdminEmailInputActionPerformed(evt);
            }
        });
        getContentPane().add(CommunityAdminEmailInput);
        CommunityAdminEmailInput.setBounds(460, 370, 150, 30);

        CommunityAdminCityLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CommunityAdminCityLabel.setText("City:");
        getContentPane().add(CommunityAdminCityLabel);
        CommunityAdminCityLabel.setBounds(410, 320, 50, 32);

        CommunityAdminCityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommunityAdminCityInputActionPerformed(evt);
            }
        });
        getContentPane().add(CommunityAdminCityInput);
        CommunityAdminCityInput.setBounds(460, 320, 150, 30);

        SubmitCommunityButton.setText("Submit");
        SubmitCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitCommunityButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitCommunityButton);
        SubmitCommunityButton.setBounds(390, 450, 100, 30);

        CloseCommunityButton.setText("Close");
        CloseCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseCommunityButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseCommunityButton);
        CloseCommunityButton.setBounds(550, 450, 100, 30);

        BackCommunityButton.setText("Back");
        BackCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackCommunityButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackCommunityButton);
        BackCommunityButton.setBounds(470, 500, 100, 30);

        BackgroundAdminPortal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemadminportalbackground.png"))); // NOI18N
        getContentPane().add(BackgroundAdminPortal);
        BackgroundAdminPortal.setBounds(0, 0, 1469, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CommunityNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityNameInputActionPerformed

    private void CommunityAdminEmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityAdminEmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityAdminEmailInputActionPerformed

    private void BackCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackCommunityButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackCommunityButtonActionPerformed

    private void CommunityAdminCityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommunityAdminCityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommunityAdminCityInputActionPerformed

    private void SubmitCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitCommunityButtonActionPerformed
        // TODO add your handling code here:
        commAdminName = CommunityNameInput.getText(); 
        commAdminCity = CommunityAdminCityInput.getText();
        commAdminEmail = CommunityAdminEmailInput.getText();
        Community community = new Community();
        
        //validation - null
        if(commAdminName.equals("") || commAdminCity.equals("") 
                || commAdminEmail.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Values All fields");
        }
        //after doctor data submit
        if(!commAdminName.equals("") && !commAdminCity.equals("") 
                && !commAdminEmail.equals(""))
        {
            submitAdminDetail = true;
            JOptionPane.showMessageDialog(this, "Community Admin's Created Successfully!"); 
        } 
        
        if (submitAdminDetail == true)
        {
            community.addCommunityAdminDetailsDir(commAdminName, commAdminCity, commAdminEmail);
//            community.writeDataIntoAFile();
        }
    }//GEN-LAST:event_SubmitCommunityButtonActionPerformed

    private void CloseCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseCommunityButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CloseCommunityButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCommunityAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCommunityAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCommunityAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCommunityAdminPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCommunityAdminPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackCommunityButton;
    private javax.swing.JLabel BackgroundAdminPortal;
    private javax.swing.JButton CloseCommunityButton;
    private javax.swing.JTextField CommunityAdminCityInput;
    private javax.swing.JLabel CommunityAdminCityLabel;
    private javax.swing.JTextField CommunityAdminEmailInput;
    private javax.swing.JLabel CommunityAdminEmailLabel;
    private javax.swing.JTextField CommunityNameInput;
    private javax.swing.JLabel CommunityNameLabel;
    private javax.swing.JLabel CommunityPageLabel;
    private javax.swing.JButton SubmitCommunityButton;
    // End of variables declaration//GEN-END:variables
}
