/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddDoctorPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String doctorName = "";
    String doctorContact = "";
    String doctorHospitalName = "";
    String doctorCommunityName = "";
    
    boolean submitDoctorData = false;
    
    public AddDoctorPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorNameLabel = new javax.swing.JLabel();
        DoctorNameInput = new javax.swing.JTextField();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorContactInput = new javax.swing.JTextField();
        DoctorHospitalLabel = new javax.swing.JLabel();
        DoctorHospitalInput = new javax.swing.JTextField();
        DoctorCommunityLabel = new javax.swing.JLabel();
        DoctorCommunityInput = new javax.swing.JTextField();
        SubmitDoctorButton = new javax.swing.JButton();
        CloseDoctorButton = new javax.swing.JButton();
        PatientPortalBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DoctorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorNameLabel.setText("Doctor's Name: ");
        getContentPane().add(DoctorNameLabel);
        DoctorNameLabel.setBounds(420, 70, 110, 40);

        DoctorNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorNameInput);
        DoctorNameInput.setBounds(530, 80, 150, 22);

        DoctorContactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorContactLabel.setText("Doctor's Contact Number: ");
        getContentPane().add(DoctorContactLabel);
        DoctorContactLabel.setBounds(350, 120, 180, 40);

        DoctorContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorContactInput);
        DoctorContactInput.setBounds(530, 130, 150, 22);

        DoctorHospitalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorHospitalLabel.setText("Doctor's Hospital Name: ");
        getContentPane().add(DoctorHospitalLabel);
        DoctorHospitalLabel.setBounds(360, 170, 170, 40);

        DoctorHospitalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorHospitalInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorHospitalInput);
        DoctorHospitalInput.setBounds(530, 180, 150, 22);

        DoctorCommunityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorCommunityLabel.setText("Doctor's Community Name: ");
        getContentPane().add(DoctorCommunityLabel);
        DoctorCommunityLabel.setBounds(340, 220, 190, 40);

        DoctorCommunityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorCommunityInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorCommunityInput);
        DoctorCommunityInput.setBounds(530, 230, 150, 22);

        SubmitDoctorButton.setText("Submit");
        SubmitDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitDoctorButton);
        SubmitDoctorButton.setBounds(490, 290, 75, 30);

        CloseDoctorButton.setText("Close");
        CloseDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseDoctorButton);
        CloseDoctorButton.setBounds(640, 290, 72, 30);

        PatientPortalBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/backgroundpatient.png"))); // NOI18N
        getContentPane().add(PatientPortalBackgroundImage);
        PatientPortalBackgroundImage.setBounds(0, 0, 1500, 715);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameInputActionPerformed

    private void DoctorCommunityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorCommunityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorCommunityInputActionPerformed

    private void SubmitDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDoctorButtonActionPerformed
        // TODO add your handling code here:
        doctorName = DoctorNameInput.getText(); 
        doctorContact = DoctorCommunityInput.getText();
        doctorHospitalName = DoctorHospitalInput.getText();
        doctorCommunityName = DoctorCommunityInput.getText();
        
        
        //validation - null
        if(doctorName.equals("") || doctorContact.equals("") 
                || doctorHospitalName.equals("") || doctorCommunityName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Values All fields");
        }
        //after doctor data submit
        if(!doctorName.equals("") && !doctorContact.equals("") 
                && !doctorHospitalName.equals("") && !doctorCommunityName.equals(""))
        {
            submitDoctorData = true;
            JOptionPane.showMessageDialog(this, "Doctor's Data Submitted!"); 
        } 
        
        if (submitDoctorData == true)
            this.dispose();
    }//GEN-LAST:event_SubmitDoctorButtonActionPerformed

    private void DoctorContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactInputActionPerformed

    private void DoctorHospitalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorHospitalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorHospitalInputActionPerformed

    private void CloseDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseDoctorButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_CloseDoctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseDoctorButton;
    private javax.swing.JTextField DoctorCommunityInput;
    private javax.swing.JLabel DoctorCommunityLabel;
    private javax.swing.JTextField DoctorContactInput;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JTextField DoctorHospitalInput;
    private javax.swing.JLabel DoctorHospitalLabel;
    private javax.swing.JTextField DoctorNameInput;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JLabel PatientPortalBackgroundImage;
    private javax.swing.JButton SubmitDoctorButton;
    // End of variables declaration//GEN-END:variables
}
