/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.util.Iterator;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddDoctorPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String doctorName = "";
    String doctorContact = "";
    String doctorHospitalName = "";
    String doctorCommunityName = "";
    DoctorDirectory doctorDirectory = new DoctorDirectory();
    
    boolean submitDoctorData = false;
    
    public AddDoctorPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientPageLabel = new javax.swing.JLabel();
        DoctorNameLabel = new javax.swing.JLabel();
        DoctorCommunityInput = new javax.swing.JTextField();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorCommunityInput1 = new javax.swing.JTextField();
        DoctorCommunityLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        DoctorCommunityLabel1 = new javax.swing.JLabel();
        DoctorNameInput = new javax.swing.JTextField();
        DoctorHospitalLabel = new javax.swing.JLabel();
        DoctorHospitalInput = new javax.swing.JTextField();
        SubmitDoctorButton = new javax.swing.JButton();
        CloseDoctorButton = new javax.swing.JButton();
        PatientPortalBackgroundImage = new javax.swing.JLabel();

        PatientPageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PatientPageLabel.setText("Doctor Information Form:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DoctorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorNameLabel.setText("Doctor's Name: ");
        getContentPane().add(DoctorNameLabel);
        DoctorNameLabel.setBounds(360, 200, 110, 30);

        DoctorCommunityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorCommunityInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorCommunityInput);
        DoctorCommunityInput.setBounds(470, 200, 210, 30);

        DoctorContactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorContactLabel.setText("Doctor's Contact Number: ");
        getContentPane().add(DoctorContactLabel);
        DoctorContactLabel.setBounds(290, 240, 180, 40);

        DoctorCommunityInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorCommunityInput1ActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorCommunityInput1);
        DoctorCommunityInput1.setBounds(470, 240, 210, 30);

        DoctorCommunityLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorCommunityLabel.setText("Email:");
        getContentPane().add(DoctorCommunityLabel);
        DoctorCommunityLabel.setBounds(420, 270, 50, 40);

        jComboBox1.setSelectedItem(Community.communityData);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(470, 360, 210, 30);

        DoctorCommunityLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorCommunityLabel1.setText("Doctor's Community Name: ");
        getContentPane().add(DoctorCommunityLabel1);
        DoctorCommunityLabel1.setBounds(280, 360, 190, 40);

        DoctorNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorNameInput);
        DoctorNameInput.setBounds(470, 280, 210, 30);

        DoctorHospitalLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorHospitalLabel.setText("Doctor's Hospital Name: ");
        getContentPane().add(DoctorHospitalLabel);
        DoctorHospitalLabel.setBounds(300, 310, 170, 40);

        DoctorHospitalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorHospitalInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorHospitalInput);
        DoctorHospitalInput.setBounds(470, 320, 210, 30);

        SubmitDoctorButton.setText("Submit");
        SubmitDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitDoctorButton);
        SubmitDoctorButton.setBounds(400, 450, 75, 30);

        CloseDoctorButton.setText("Close");
        CloseDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CloseDoctorButton);
        CloseDoctorButton.setBounds(580, 450, 72, 30);

        PatientPortalBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemadminportalbackground.png"))); // NOI18N
        getContentPane().add(PatientPortalBackgroundImage);
        PatientPortalBackgroundImage.setBounds(-30, 0, 1469, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameInputActionPerformed

    private void DoctorCommunityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorCommunityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorCommunityInputActionPerformed

    private void SubmitDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDoctorButtonActionPerformed
        // TODO add your handling code here:
        doctorName = DoctorNameInput.getText(); 
        doctorContact = DoctorCommunityInput.getText();
        doctorHospitalName = DoctorHospitalInput.getText();
        doctorCommunityName = DoctorCommunityInput.getText();
        
        
        //validation - null
        if(doctorName.equals("") || doctorContact.equals("") 
                || doctorHospitalName.equals("") || doctorCommunityName.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Values All fields");
        }
        //after doctor data submit
        if(!doctorName.equals("") && !doctorContact.equals("") 
                && !doctorHospitalName.equals("") && !doctorCommunityName.equals(""))
        {
            submitDoctorData = true;
            JOptionPane.showMessageDialog(this, "Doctor's Data Submitted!"); 
        } 
        
        if (submitDoctorData == true)
        {
            doctorDirectory.addDoctorDataInDirectory(doctorName, doctorName, doctorHospitalName, doctorCommunityName);
            this.dispose();
        }
    }//GEN-LAST:event_SubmitDoctorButtonActionPerformed

    private void DoctorHospitalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorHospitalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorHospitalInputActionPerformed

    private void CloseDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseDoctorButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_CloseDoctorButtonActionPerformed

    private void DoctorCommunityInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorCommunityInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorCommunityInput1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setModel(new DefaultComboBoxModel<String>(Community.communityData.toArray(new String[0]))); 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseDoctorButton;
    private javax.swing.JTextField DoctorCommunityInput;
    private javax.swing.JTextField DoctorCommunityInput1;
    private javax.swing.JLabel DoctorCommunityLabel;
    private javax.swing.JLabel DoctorCommunityLabel1;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JTextField DoctorHospitalInput;
    private javax.swing.JLabel DoctorHospitalLabel;
    private javax.swing.JTextField DoctorNameInput;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JLabel PatientPageLabel;
    private javax.swing.JLabel PatientPortalBackgroundImage;
    private javax.swing.JButton SubmitDoctorButton;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
