/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class AddDoctorPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String DoctorName = "";
    String DoctorContact = "";
    
    public AddDoctorPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DoctorNameLabel = new javax.swing.JLabel();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorNameInput = new javax.swing.JTextField();
        DoctorContactInput = new javax.swing.JTextField();
        SubmitDoctorButton = new javax.swing.JButton();
        CloseDoctorButton = new javax.swing.JButton();
        DoctorContactLabel1 = new javax.swing.JLabel();
        DoctorContactInput1 = new javax.swing.JTextField();
        DoctorContactLabel2 = new javax.swing.JLabel();
        DoctorContactInput2 = new javax.swing.JTextField();
        PatientPortalBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DoctorNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorNameLabel.setText("Doctor's Name: ");
        getContentPane().add(DoctorNameLabel);
        DoctorNameLabel.setBounds(420, 70, 110, 40);

        DoctorContactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorContactLabel.setText("Doctor's Community Name: ");
        getContentPane().add(DoctorContactLabel);
        DoctorContactLabel.setBounds(340, 220, 190, 40);

        DoctorNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorNameInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorNameInput);
        DoctorNameInput.setBounds(530, 80, 150, 22);

        DoctorContactInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactInputActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorContactInput);
        DoctorContactInput.setBounds(530, 230, 150, 22);

        SubmitDoctorButton.setText("Submit");
        SubmitDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitDoctorButton);
        SubmitDoctorButton.setBounds(490, 290, 75, 30);

        CloseDoctorButton.setText("Close");
        getContentPane().add(CloseDoctorButton);
        CloseDoctorButton.setBounds(640, 290, 72, 30);

        DoctorContactLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorContactLabel1.setText("Doctor's Contact Number: ");
        getContentPane().add(DoctorContactLabel1);
        DoctorContactLabel1.setBounds(350, 120, 180, 40);

        DoctorContactInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactInput1ActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorContactInput1);
        DoctorContactInput1.setBounds(530, 130, 150, 22);

        DoctorContactLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DoctorContactLabel2.setText("Doctor's Hospital Name: ");
        getContentPane().add(DoctorContactLabel2);
        DoctorContactLabel2.setBounds(360, 170, 170, 40);

        DoctorContactInput2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorContactInput2ActionPerformed(evt);
            }
        });
        getContentPane().add(DoctorContactInput2);
        DoctorContactInput2.setBounds(530, 180, 150, 22);

        PatientPortalBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/backgroundpatient.png"))); // NOI18N
        getContentPane().add(PatientPortalBackgroundImage);
        PatientPortalBackgroundImage.setBounds(0, 0, 1500, 715);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoctorNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorNameInputActionPerformed

    private void DoctorContactInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactInputActionPerformed

    private void SubmitDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDoctorButtonActionPerformed
        // TODO add your handling code here:
        DoctorName = DoctorNameInput.getText(); 
        DoctorContact = DoctorContactInput.getText();
        
//        Doctor doctor = new Doctor(); 
//        password = PasswordTextField.getText();
//        role = personInfo.getRoleValue(username);
//        
//        //validation - null
//        if(username.equals("") && password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Enter Username and Password");
//        }
//        else if(!(username.equals("")) && password.equals(""))
//        {
//            JOptionPane.showMessageDialog(this, "Enter Password");        
//        }
//        else if(username.equals("") && !(password.equals("")))
//        {
//            JOptionPane.showMessageDialog(this, "Enter Username");    
//        }
//        
//        System.out.println("username "+username);
//        System.out.println("password "+password);
//        
//        //validation - actual data
//        Iterator<Map.Entry<String, String> > iterator = personInfo.loginInfo.entrySet().iterator();
//        boolean isKeyPresent = false;
//        while (iterator.hasNext()) 
//        {
//            Map.Entry<String, String> entry = iterator.next();
//            if(username.equals(entry.getKey()))
//            {
//                isKeyPresent = true;
//            }
//        }
//        
//        if(isKeyPresent == true && personInfo.getPasswordValue(username).equals(password))
//        {
//            JOptionPane.showMessageDialog(this, "Got Access!"); 
//            CommonPortal commonPortal = new CommonPortal();
//            commonPortal.setSize(1500, 720);
//            commonPortal.setVisible(true);
//            this.dispose();
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(this, "Login Unsuccessful!");
//            this.dispose();
//
//        }
//    }   
        
    }//GEN-LAST:event_SubmitDoctorButtonActionPerformed

    private void DoctorContactInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactInput1ActionPerformed

    private void DoctorContactInput2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorContactInput2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorContactInput2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDoctorPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDoctorPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseDoctorButton;
    private javax.swing.JTextField DoctorContactInput;
    private javax.swing.JTextField DoctorContactInput1;
    private javax.swing.JTextField DoctorContactInput2;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JLabel DoctorContactLabel1;
    private javax.swing.JLabel DoctorContactLabel2;
    private javax.swing.JTextField DoctorNameInput;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JLabel PatientPortalBackgroundImage;
    private javax.swing.JButton SubmitDoctorButton;
    // End of variables declaration//GEN-END:variables
}
