/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

/**
 *
 * @author ASUS
 */
public class AddHospitalPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    public AddHospitalPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientPageLabel = new javax.swing.JLabel();
        NamePatientLabel = new javax.swing.JLabel();
        NamePatientInput = new javax.swing.JTextField();
        ContactNumPatientLabel = new javax.swing.JLabel();
        ContactNumPatientInput = new javax.swing.JTextField();
        EmailPatientLabel = new javax.swing.JLabel();
        EmailPatientInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        EmailPatientLabel1 = new javax.swing.JLabel();
        EmailPatientInput1 = new javax.swing.JTextField();
        BackgroundAdminPortal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PatientPageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PatientPageLabel.setText("Hospital Information Form:");
        getContentPane().add(PatientPageLabel);
        PatientPageLabel.setBounds(340, 210, 340, 32);

        NamePatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamePatientLabel.setText("Name:");
        getContentPane().add(NamePatientLabel);
        NamePatientLabel.setBounds(410, 270, 40, 32);

        NamePatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(NamePatientInput);
        NamePatientInput.setBounds(460, 270, 150, 30);

        ContactNumPatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ContactNumPatientLabel.setText("Contact Number: ");
        getContentPane().add(ContactNumPatientLabel);
        ContactNumPatientLabel.setBounds(350, 330, 100, 32);

        ContactNumPatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumPatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNumPatientInput);
        ContactNumPatientInput.setBounds(460, 330, 150, 30);

        EmailPatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailPatientLabel.setText("Community:");
        getContentPane().add(EmailPatientLabel);
        EmailPatientLabel.setBounds(380, 440, 70, 32);

        EmailPatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailPatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(EmailPatientInput);
        EmailPatientInput.setBounds(460, 440, 150, 30);

        SubmitButton.setText("Submit");
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(380, 510, 100, 30);

        CloseButton.setText("Close");
        getContentPane().add(CloseButton);
        CloseButton.setBounds(580, 510, 100, 30);

        EmailPatientLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailPatientLabel1.setText("City:");
        getContentPane().add(EmailPatientLabel1);
        EmailPatientLabel1.setBounds(420, 390, 40, 32);

        EmailPatientInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailPatientInput1ActionPerformed(evt);
            }
        });
        getContentPane().add(EmailPatientInput1);
        EmailPatientInput1.setBounds(460, 390, 150, 30);

        BackgroundAdminPortal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemadminportalbackground.png"))); // NOI18N
        getContentPane().add(BackgroundAdminPortal);
        BackgroundAdminPortal.setBounds(0, 0, 1469, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailPatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPatientInputActionPerformed

    private void NamePatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamePatientInputActionPerformed

    private void ContactNumPatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumPatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumPatientInputActionPerformed

    private void EmailPatientInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPatientInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPatientInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddHospitalPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddHospitalPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddHospitalPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddHospitalPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddHospitalPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundAdminPortal;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField ContactNumPatientInput;
    private javax.swing.JLabel ContactNumPatientLabel;
    private javax.swing.JTextField EmailPatientInput;
    private javax.swing.JTextField EmailPatientInput1;
    private javax.swing.JLabel EmailPatientLabel;
    private javax.swing.JLabel EmailPatientLabel1;
    private javax.swing.JTextField NamePatientInput;
    private javax.swing.JLabel NamePatientLabel;
    private javax.swing.JLabel PatientPageLabel;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
