/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.security.SecureRandom;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AddPatientPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String age = "";
    String contactNumPatient = "";
    String emailPatient = "";
    String namePatient = "";
    String gender = "";
    String password = "";
    //set radio button
    ButtonGroup group = null;
    PatientDirectory patientDirectory = null;
    
    public AddPatientPortal() {
        initComponents();
        MaleGenderPatientButton.setSelected(true);     
        group = new ButtonGroup();//used to store all radio buttons.
        group.add(MaleGenderPatientButton);
        group.add(FemaleGenderPatientButton);
        patientDirectory = new PatientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public String generateRandomPassword(int len)
    {
        // ASCII range – alphanumeric (0-9, a-z, A-Z)
        final String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
 
        SecureRandom random = new SecureRandom();
        StringBuilder sb = new StringBuilder();
 
        // each iteration of the loop randomly chooses a character from the given
        // ASCII range and appends it to the `StringBuilder` instance
 
        for (int i = 0; i < len; i++)
        {
            int randomIndex = random.nextInt(chars.length());
            sb.append(chars.charAt(randomIndex));
        }
 
        return sb.toString();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientPageLabel = new javax.swing.JLabel();
        NamePatientLabel = new javax.swing.JLabel();
        NamePatientInput = new javax.swing.JTextField();
        AgePatientLabel = new javax.swing.JLabel();
        AgePatientInput = new javax.swing.JTextField();
        GenderPatientLabel = new javax.swing.JLabel();
        MaleGenderPatientButton = new javax.swing.JRadioButton();
        FemaleGenderPatientButton = new javax.swing.JRadioButton();
        ContactNumPatientLabel = new javax.swing.JLabel();
        ContactNumPatientInput = new javax.swing.JTextField();
        EmailPatientLabel = new javax.swing.JLabel();
        EmailPatientInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackgroundAdminPortal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PatientPageLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PatientPageLabel.setText("Person Information Form:");
        getContentPane().add(PatientPageLabel);
        PatientPageLabel.setBounds(400, 210, 340, 32);

        NamePatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamePatientLabel.setText("Name:");
        getContentPane().add(NamePatientLabel);
        NamePatientLabel.setBounds(406, 270, 40, 32);

        NamePatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamePatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(NamePatientInput);
        NamePatientInput.setBounds(460, 270, 150, 30);

        AgePatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgePatientLabel.setText("Age: ");
        getContentPane().add(AgePatientLabel);
        AgePatientLabel.setBounds(420, 320, 30, 32);

        AgePatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgePatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(AgePatientInput);
        AgePatientInput.setBounds(460, 320, 50, 30);

        GenderPatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenderPatientLabel.setText("Gender:");
        getContentPane().add(GenderPatientLabel);
        GenderPatientLabel.setBounds(400, 370, 50, 32);

        MaleGenderPatientButton.setText("Male");
        getContentPane().add(MaleGenderPatientButton);
        MaleGenderPatientButton.setBounds(460, 371, 60, 30);

        FemaleGenderPatientButton.setText("Female");
        FemaleGenderPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleGenderPatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FemaleGenderPatientButton);
        FemaleGenderPatientButton.setBounds(540, 370, 80, 30);

        ContactNumPatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ContactNumPatientLabel.setText("Contact Number: ");
        getContentPane().add(ContactNumPatientLabel);
        ContactNumPatientLabel.setBounds(350, 420, 100, 32);

        ContactNumPatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumPatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNumPatientInput);
        ContactNumPatientInput.setBounds(460, 420, 150, 30);

        EmailPatientLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailPatientLabel.setText("Email:");
        getContentPane().add(EmailPatientLabel);
        EmailPatientLabel.setBounds(410, 470, 40, 32);

        EmailPatientInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailPatientInputActionPerformed(evt);
            }
        });
        getContentPane().add(EmailPatientInput);
        EmailPatientInput.setBounds(460, 470, 210, 30);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(380, 530, 100, 30);

        CloseButton.setText("Close");
        getContentPane().add(CloseButton);
        CloseButton.setBounds(570, 530, 100, 30);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(480, 580, 100, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "LoginId", "Password"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 260, 452, 330);

        BackgroundAdminPortal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemadminportalbackground.png"))); // NOI18N
        getContentPane().add(BackgroundAdminPortal);
        BackgroundAdminPortal.setBounds(0, 0, 1469, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgePatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgePatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgePatientInputActionPerformed

    private void EmailPatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailPatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailPatientInputActionPerformed

    private void FemaleGenderPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleGenderPatientButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleGenderPatientButtonActionPerformed

    private void NamePatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamePatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamePatientInputActionPerformed

    private void ContactNumPatientInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumPatientInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumPatientInputActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        age = AgePatientInput.getText().toLowerCase(); 
        contactNumPatient = ContactNumPatientInput.getText();
        emailPatient = EmailPatientInput.getText();
        namePatient = NamePatientInput.getText();
        gender = group.getSelection().toString();
        
        //validation - null
        if(age.equals("") || contactNumPatient.equals("") || emailPatient.equals("")
                || namePatient.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter All Fields!");
        }
        
        if(!age.equals("") && !contactNumPatient.equals("") 
                && !emailPatient.equals("") && !namePatient.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Patient Data Submitted Successfully!");
            password = generateRandomPassword(8);
            //display data into table model
            patientDirectory.addPatientDataInDirectory(namePatient, contactNumPatient, age, gender, emailPatient, password);
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.addRow(new Object[]{emailPatient, password});
            //reset
            AgePatientInput.setText("");
            ContactNumPatientInput.setText("");
            EmailPatientInput.setText("");
            NamePatientInput.setText("");
            MaleGenderPatientButton.setSelected(true);  
        }
        
        
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPatientPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPatientPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgePatientInput;
    private javax.swing.JLabel AgePatientLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BackgroundAdminPortal;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField ContactNumPatientInput;
    private javax.swing.JLabel ContactNumPatientLabel;
    private javax.swing.JTextField EmailPatientInput;
    private javax.swing.JLabel EmailPatientLabel;
    private javax.swing.JRadioButton FemaleGenderPatientButton;
    private javax.swing.JLabel GenderPatientLabel;
    private javax.swing.JRadioButton MaleGenderPatientButton;
    private javax.swing.JTextField NamePatientInput;
    private javax.swing.JLabel NamePatientLabel;
    private javax.swing.JLabel PatientPageLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
