/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

/**
 *
 * @author ASUS
 */
public class CommonPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    public CommonPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        SearchDoctorHospital = new javax.swing.JScrollPane();
        SearchDocHospTable = new javax.swing.JTable();
        AddDoctorButton = new javax.swing.JButton();
        PatientPortalBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().setLayout(null);

        SearchTextField.setText("Write your search text here");
        getContentPane().add(SearchTextField);
        SearchTextField.setBounds(160, 40, 230, 22);

        SearchButton.setText("Search Button");
        getContentPane().add(SearchButton);
        SearchButton.setBounds(30, 40, 103, 23);

        SearchDocHospTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Doctor", "Hospital", "City", "Community"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        SearchDoctorHospital.setViewportView(SearchDocHospTable);

        getContentPane().add(SearchDoctorHospital);
        SearchDoctorHospital.setBounds(30, 80, 360, 380);

        AddDoctorButton.setText("Add Doctor");
        AddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddDoctorButton);
        AddDoctorButton.setBounds(30, 490, 120, 23);

        PatientPortalBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/communityadminbackgroundimage.jpg"))); // NOI18N
        PatientPortalBackgroundImage.setMaximumSize(new java.awt.Dimension(1500, 720));
        PatientPortalBackgroundImage.setMinimumSize(new java.awt.Dimension(1500, 720));
        PatientPortalBackgroundImage.setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().add(PatientPortalBackgroundImage);
        PatientPortalBackgroundImage.setBounds(-20, 0, 1500, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorButtonActionPerformed
        // TODO add your handling code here:
        
        LoginWindowAllUsers hospitalAdminPortal = new LoginWindowAllUsers();
        if(!hospitalAdminPortal.role.equals("hosp adm"))
        {
            AddDoctorButton.setEnabled(false);
        }
        else
        {
            //hospital admin
            //this.dispose();
            AddDoctorPortal addDoctorPortal = new AddDoctorPortal();
            addDoctorPortal.setSize(1500, 720);
            addDoctorPortal.setVisible(true);
            //to add doctor call doctor class here
        }
    }//GEN-LAST:event_AddDoctorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommonPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommonPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommonPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommonPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommonPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorButton;
    private javax.swing.JLabel PatientPortalBackgroundImage;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTable SearchDocHospTable;
    private javax.swing.JScrollPane SearchDoctorHospital;
    private javax.swing.JTextField SearchTextField;
    // End of variables declaration//GEN-END:variables
}
