/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

/**
 *
 * @author ASUS
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SysAdminLoginImage = new javax.swing.JLabel();
        PatientLoginImage = new javax.swing.JLabel();
        DoctorLoginImage = new javax.swing.JLabel();
        HospitalAdminLoginImage = new javax.swing.JLabel();
        CommunityAdminLoginImage = new javax.swing.JLabel();
        CommAdminLoginButton = new javax.swing.JButton();
        SysAdminLoginButton = new javax.swing.JButton();
        PatientLoginButton = new javax.swing.JButton();
        DoctorLoginButton = new javax.swing.JButton();
        HospitalAdminLoginButton = new javax.swing.JButton();
        LoginBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        SysAdminLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/systemadminlogin.png"))); // NOI18N
        jPanel1.add(SysAdminLoginImage);
        SysAdminLoginImage.setBounds(30, 220, 360, 330);

        PatientLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/patientloginimage.png"))); // NOI18N
        jPanel1.add(PatientLoginImage);
        PatientLoginImage.setBounds(280, 260, 230, 240);

        DoctorLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/doctorloginimage.png"))); // NOI18N
        jPanel1.add(DoctorLoginImage);
        DoctorLoginImage.setBounds(530, 270, 240, 240);

        HospitalAdminLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/hospitaladminloginimage.jpg"))); // NOI18N
        jPanel1.add(HospitalAdminLoginImage);
        HospitalAdminLoginImage.setBounds(770, 270, 210, 230);

        CommunityAdminLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/communityadminloginimage.jpg"))); // NOI18N
        jPanel1.add(CommunityAdminLoginImage);
        CommunityAdminLoginImage.setBounds(1010, 270, 250, 230);

        CommAdminLoginButton.setText("COMMUNITY ADMIN");
        CommAdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommAdminLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CommAdminLoginButton);
        CommAdminLoginButton.setBounds(1050, 530, 150, 30);

        SysAdminLoginButton.setText("SYSTEM ADMIN");
        SysAdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SysAdminLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SysAdminLoginButton);
        SysAdminLoginButton.setBounds(70, 530, 130, 30);

        PatientLoginButton.setText("PATIENT");
        PatientLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PatientLoginButton);
        PatientLoginButton.setBounds(350, 530, 114, 30);

        DoctorLoginButton.setText("DOCTOR");
        DoctorLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DoctorLoginButton);
        DoctorLoginButton.setBounds(590, 530, 114, 30);

        HospitalAdminLoginButton.setText("HOSPITAL ADMIN");
        HospitalAdminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalAdminLoginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HospitalAdminLoginButton);
        HospitalAdminLoginButton.setBounds(810, 530, 140, 30);

        LoginBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/hmbackground.png"))); // NOI18N
        jPanel1.add(LoginBackgroundImage);
        LoginBackgroundImage.setBounds(0, 20, 1500, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SysAdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SysAdminLoginButtonActionPerformed
        // TODO add your handling code here:
        SystemAdminPortal systemAdminPortal = new SystemAdminPortal();
        systemAdminPortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SysAdminLoginButtonActionPerformed

    private void PatientLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientLoginButtonActionPerformed
        // TODO add your handling code here:
        PatientPortal patientPortal = new PatientPortal();
        patientPortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientLoginButtonActionPerformed

    private void DoctorLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorLoginButtonActionPerformed
        // TODO add your handling code here:
        DoctorPortal doctorPortal = new DoctorPortal();
        doctorPortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DoctorLoginButtonActionPerformed

    private void HospitalAdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalAdminLoginButtonActionPerformed
        // TODO add your handling code here:
        HospitalAdminPortal hospitalAdmin = new HospitalAdminPortal();
        hospitalAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HospitalAdminLoginButtonActionPerformed

    private void CommAdminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommAdminLoginButtonActionPerformed
        // TODO add your handling code here:
        CommunityAdminPortal communityAdminPortal = new CommunityAdminPortal();
        communityAdminPortal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CommAdminLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CommAdminLoginButton;
    private javax.swing.JLabel CommunityAdminLoginImage;
    private javax.swing.JButton DoctorLoginButton;
    private javax.swing.JLabel DoctorLoginImage;
    private javax.swing.JButton HospitalAdminLoginButton;
    private javax.swing.JLabel HospitalAdminLoginImage;
    private javax.swing.JLabel LoginBackgroundImage;
    private javax.swing.JButton PatientLoginButton;
    private javax.swing.JLabel PatientLoginImage;
    private javax.swing.JButton SysAdminLoginButton;
    private javax.swing.JLabel SysAdminLoginImage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
