/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class LoginWindowSystemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String username = "";
    String password = "";
    String role = "";
    
    public LoginWindowSystemAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPortalLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        PasswordTextField = new javax.swing.JPasswordField();
        HospitalPortalBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        LoginPortalLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LoginPortalLabel.setText("Username:");
        getContentPane().add(LoginPortalLabel);
        LoginPortalLabel.setBounds(470, 230, 110, 60);

        UsernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UsernameLabel.setText("Password:");
        getContentPane().add(UsernameLabel);
        UsernameLabel.setBounds(470, 290, 100, 40);

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        PasswordLabel.setText("System Admin Login Portal:");
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(430, 100, 510, 130);

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameTextField);
        UsernameTextField.setBounds(570, 250, 190, 30);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(220, 50, 150, 32);

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(520, 380, 150, 32);

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTextField);
        PasswordTextField.setBounds(570, 300, 190, 30);

        HospitalPortalBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagementportal/hospitaladminbackgroundimage.jpg"))); // NOI18N
        HospitalPortalBackground.setMaximumSize(new java.awt.Dimension(1500, 720));
        HospitalPortalBackground.setMinimumSize(new java.awt.Dimension(1500, 720));
        HospitalPortalBackground.setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().add(HospitalPortalBackground);
        HospitalPortalBackground.setBounds(0, 0, 1500, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        PersonDirectory personInfo = new PersonDirectory();
        username = UsernameTextField.getText().toLowerCase(); 
        password = PasswordTextField.getText();
        role = personInfo.getSysAdminRoleValue(username);
        
        //validation - null
        if(username.equals("") && password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Username and Password");
        }
        else if(!(username.equals("")) && password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Password");        
        }
        else if(username.equals("") && !(password.equals("")))
        {
            JOptionPane.showMessageDialog(this, "Enter Username");    
        }
        
        System.out.println("username "+username);
        System.out.println("password "+password);
        
        //validation - actual data
        Iterator<Map.Entry<String, String> > iterator = personInfo.loginInfo.entrySet().iterator();
        boolean isKeyPresent = false;
        while (iterator.hasNext()) 
        {
            Map.Entry<String, String> entry = iterator.next();
            if(username.equals(entry.getKey()))
            {
                isKeyPresent = true;
            }
        }
        
        if(isKeyPresent == true && personInfo.getSysAdminPasswordValue(username).equals(password))
        {
            JOptionPane.showMessageDialog(this, "Got Access!"); 
            CommonPortal commonPortal = new CommonPortal();
            commonPortal.setSize(1500, 720);
            commonPortal.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Login Unsuccessful!");
            this.dispose();

        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
//            this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginWindowSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginWindowSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginWindowSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginWindowSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindowSystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel HospitalPortalBackground;
    private javax.swing.JLabel LoginPortalLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    // End of variables declaration//GEN-END:variables
}
