/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class PatientLoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    String email = "";
    String password = "";
    String role = "";
    PatientDirectory patientDirectory = null;
    
    public PatientLoginWindow() {
        initComponents();
        patientDirectory = new PatientDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmailLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PageLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        BackButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        HospitalPortalBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        EmailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EmailLabel.setText("Email:");
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(500, 230, 60, 60);

        PasswordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PasswordLabel.setText("Password:");
        getContentPane().add(PasswordLabel);
        PasswordLabel.setBounds(470, 290, 100, 40);

        PageLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        PageLabel.setText("Patient Login Portal:");
        getContentPane().add(PageLabel);
        PageLabel.setBounds(430, 100, 510, 130);

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailTextField);
        EmailTextField.setBounds(570, 250, 190, 30);

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordTextField);
        PasswordTextField.setBounds(570, 300, 190, 30);

        BackButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(220, 50, 150, 32);

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitButton);
        SubmitButton.setBounds(610, 360, 110, 32);

        HospitalPortalBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospitaladminbackgroundimage.jpg"))); // NOI18N
        HospitalPortalBackground.setMaximumSize(new java.awt.Dimension(1500, 720));
        HospitalPortalBackground.setMinimumSize(new java.awt.Dimension(1500, 720));
        HospitalPortalBackground.setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().add(HospitalPortalBackground);
        HospitalPortalBackground.setBounds(0, 0, 1500, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        PersonDirectory personInfo = new PersonDirectory();
        email = EmailTextField.getText().toLowerCase(); 
        password = PasswordTextField.getText();
        
        //validation - null
        if(email.equals("") && password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Username and Password");
        }
        else if(!(email.equals("")) && password.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Enter Password");        
        }
        else if(email.equals("") && !(password.equals("")))
        {
            JOptionPane.showMessageDialog(this, "Enter Username");    
        }
        
        System.out.println("username "+email);
        System.out.println("password "+password);
        
        //validation - actual data
        if(patientDirectory.map.containsKey(email))
        {
            //Search Doc window
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
            this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientLoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientLoginWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel HospitalPortalBackground;
    private javax.swing.JLabel PageLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton SubmitButton;
    // End of variables declaration//GEN-END:variables
}
