/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagementportal;

/**
 *
 * @author ASUS
 */
public class SystemAdminTasksPortal extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPortal
     */
    public SystemAdminTasksPortal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCommunityAdminButton = new javax.swing.JButton();
        Note3 = new javax.swing.JLabel();
        AddDoctorButton = new javax.swing.JButton();
        AddPatientButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        PatientPortalBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        AddCommunityAdminButton.setText("Add Community Admin");
        AddCommunityAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCommunityAdminButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddCommunityAdminButton);
        AddCommunityAdminButton.setBounds(580, 470, 240, 50);

        Note3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Note3.setText("Select a Task to Perform:");
        getContentPane().add(Note3);
        Note3.setBounds(550, 200, 310, 32);

        AddDoctorButton.setText("Add Doctor");
        AddDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddDoctorButton);
        AddDoctorButton.setBounds(580, 260, 240, 50);

        AddPatientButton.setText("Add Patient");
        AddPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddPatientButton);
        AddPatientButton.setBounds(580, 360, 240, 50);

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(330, 210, 110, 40);

        PatientPortalBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/systemadminportalbackground.png"))); // NOI18N
        PatientPortalBackgroundImage.setMaximumSize(new java.awt.Dimension(1500, 720));
        PatientPortalBackgroundImage.setMinimumSize(new java.awt.Dimension(1500, 720));
        PatientPortalBackgroundImage.setPreferredSize(new java.awt.Dimension(1500, 720));
        getContentPane().add(PatientPortalBackgroundImage);
        PatientPortalBackgroundImage.setBounds(-20, 0, 1500, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCommunityAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCommunityAdminButtonActionPerformed
        // TODO add your handling code here:
        AddCommunityAdminPortal addCommunityAdminPortal = new AddCommunityAdminPortal();
        addCommunityAdminPortal.setSize(1500, 720);
        addCommunityAdminPortal.setVisible(true);
//        this.dispose(); used after back button
    }//GEN-LAST:event_AddCommunityAdminButtonActionPerformed

    private void AddDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorButtonActionPerformed
        // TODO add your handling code here:
        AddDoctorPortal addDoctorPortal = new AddDoctorPortal();
        addDoctorPortal.setSize(1500, 720);
        addDoctorPortal.setVisible(true);
//        this.dispose(); used after back button
    }//GEN-LAST:event_AddDoctorButtonActionPerformed

    private void AddPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientButtonActionPerformed
        // TODO add your handling code here:
        AddPatientPortal addPatientPortal = new AddPatientPortal();
        addPatientPortal.setSize(1500, 720);
        addPatientPortal.setVisible(true);
//        this.dispose(); used after back button
    }//GEN-LAST:event_AddPatientButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminTasksPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminTasksPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminTasksPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminTasksPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdminTasksPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCommunityAdminButton;
    private javax.swing.JButton AddDoctorButton;
    private javax.swing.JButton AddPatientButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Note3;
    private javax.swing.JLabel PatientPortalBackgroundImage;
    // End of variables declaration//GEN-END:variables
}
